# Generated by Django 3.2.8 on 2024-02-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orcapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='creditinformation',
        ),
    ]
