# Generated by Django 3.2.8 on 2024-04-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orcapp', '0004_laonrepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanrepay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('paid', models.IntegerField()),
                ('left', models.IntegerField()),
                ('months_paid', models.IntegerField()),
                ('months_left', models.IntegerField()),
                ('emi_amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='laonrepay',
        ),
    ]
